---
- hosts: local
  vars:
    userFile: /home/ec2-user/RHELAnsible/vars/list
  tasks:
    - name: create file
      file:
        state: touch
        path: "{{ userFile }}"
    - name: list users
      lineinfile: 
        path: "{{ userFile }}"
        line: "{{ item }}"
      with_items:
        - "{{ staff}}"
        - "{{ faculty }}"
        - "{{ others }}"

