--- # copy module example
- hosts: all
  user: ec2-user
  connection: ssh
  become: yes
  tasks:
    - name: Copy from from the files directory test file
      action: copy src=need_dir.sh dest=/home/ec2-user/need_dir.sh owner=ec2-user group=ec2-user mode=0777 
