--- # debug module example
- hosts: apacheweb
  user: ec2-user
  connection: ssh
  become: true
  tasks:
    - name: Install the web server
      yum: name=httpd state=installed
    - debug: msg="Equivalent of sudo yum install httpd"
    - name: How long the system is up
      shell: /usr/bin/uptime
      register: up_result
    - debug: var=up_result
