--- # Fetch module sample
- hosts: all
  user: ec2-user
  become: true
  connection: ssh
  tasks:
    - name: Copy remote host file to locaal server
      fetch: src=/etc/hosts dest=/home/ec2-user/prefix-{{ansible_hostname}} flat=yes
