--- # SEBoolean Example
- hosts: apacheweb
  user: ec2-user
  become: true
  connection: ssh
  gather_facts: no
  tasks:
    - name: Change the boolean for anonymous write to the web server
      seboolean: name=httpd_anon_write state=no persistent=yes
