--- # unarchive module example
- hosts: apacheweb
  user: ec2-user
  become: true
  connection: ssh
  gather_facts: no
  tasks:
    - name: copy and unarchive a file
      unarchive: src=/home/ec2-user/test.tar.gz dest=/home/ec2-user/temp copy=no
