--- # until example
- hosts: apacheweb
  become: yes
  connection: ssh
  gather_facts: no
  user: ec2-user
  tasks:
    - name: Installing apache webserver
      yum: pkg=httpd state=latest
    - name: Verify Service Status
      shell: systemctl status httpd
      register: result
      until: result.stdout.find("active(running)") != -1
      retries: 5
      delay: 5
    - debug: var=result
