--- # sample user module
- hosts: apacheweb
  connection: ssh
  become: true
  user: ec2-user
  gather_facts: no
  tasks:
    - name: Add a user named apache-test
      user: name=apache-test state=absent remove=yes
