--- # wait for module
- hosts: apacheweb
  become: true
  gather_facts: no
  tasks:
    - name: Install Apache Tomcat
      action: yum name=tomcat state=installed
    - name: Waiting for port 8080 to listen
      wait_for:
        port: 8080
        state: started
    - name: verifying lynx installation
      action: yum name=lynx state=latest
