--- #sample when playbook 
- hosts: aptserver
  user: ec2-user
  connection: ssh
  become: yes
  vars:
    playbook_type: conditionalexample
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  tasks:
    - name: Install apche to the distribution type
      command: apt-get -y install apache2
      when: ansible_os_family=='Debian'
    - name: Install apache on RHEL
      command: yum -y install httpd
      when: ansible_os_family== 'RedHat'
