---
- hosts: local
  vars_files:
    - /home/ec2-user/RHELAnsible/vaults/secure
  tasks:
    - name: Output message
      shell: echo {{ message }} > /home/ec2-user/RHELAnsible/vaults/deployed.txt
      no_log: true
