---
- hosts: apacheweb
  become: true
  tasks:
    - name: Install apache web server
      yum: 
        name: httpd
        state: latest
    - name: Restart HTTPD
      service: 
        name: httpd
        state: started
        enabled: yes
    - name: Create index.html
      file:
        path: /var/www/html/index.html
        state: touch
    - name: add aline in index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "Hello World"

