---
- hosts: appserver
  become: yes
  serial:
    - 1
    - 2
    - 50%
  max_fail_percentage: 30
  tasks:
    - name: add host entry
      lineinfile:
        path: /etc/hosts
        line: "server2 server2.myansible.com"
